package com.example.chat_poc.config

/**
 * Connect config baked in at library build time from local.properties.
 * Do not edit; generated by Gradle task generateConnectConfig.
 */
object LibraryConnectConfig {
    fun get(): ConnectConfig? = if (hasConfig) ConnectConfig(
        apiGatewayUrl = "https://fbh2ewfqec.execute-api.ca-central-1.amazonaws.com/prod/start-chat",
        contactFlowId = "a03ee512-0f2a-41ca-913d-230dd808a15a",
        instanceId = "2eaab74c-6372-4d38-b1db-9ded531b86c7",
        region = "ca-central-1"
    ) else null

    private const val hasConfig = true
}